### ISSUE TITLE
Fix uploaded image not being reset on new order.

### ISSUE THREAD

**Issue by ryvix** [milliondollarscript/milliondollarscript#19]
***In GitLab by @Ryvix on Dec 8, 2023, 21:41 EST:***

*Migrated from GitLab: https://gitlab.com/MillionDollarScript/milliondollarscript-two/-/work_items/18*

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Dec 29, 2023, 17:38 EST:***

removed parent issue #17
