### ISSUE TITLE
I can't save the grid

### ISSUE THREAD

**Issue by ahmethil** [MillionDollarScript/MillionDollarScript#24]
When I click on new grid I am able to fill in the fields except currency. Also I am not able to save the grid, there is no save button. How can I solve this problem?
![grid issue](https://cloud.githubusercontent.com/assets/11898348/7100958/bffb82e4-e03e-11e4-84d0-3c1699b0798e.png)

**Comment by ty2u** [comment]
Hmm this looks like maybe the entire page isn't loading properly. Do you see any errors in your error logs?
