### ISSUE TITLE
How to install on wix.com

### ISSUE THREAD

**Issue by babisonashok** [MillionDollarScript/MillionDollarScript#26]
Hey I created a website on Wix.com and I don't have a clue on how to install the script into the webite can anyone help me out?

**Comment by ty2u** [comment]
Does wix even have php and mysql?

**Comment by babisonashok** [comment]
no but i can transfer the website over to a another website creator do you know what website that creates websites that can install script so i can transfer my website over to this one

**Comment by ty2u** [comment]
I'm not sure exactly. Anything that supports a somewhat recent version of php and mysql. You could use something like hostgator and install WordPress and this script on the same site.

**Comment by babisonashok** [comment]
hey can you tell me if this website creator is fine for installing scripts http://www.000webhost.com/ thanks alot

**Comment by ty2u** [comment]
Well it says it has php and mysql but if you plan to go with a free host you will likely run into issues with resources such as memory.

**Comment by babisonashok** [comment]
ok thank you i will give your website a try but which option

**Comment by ty2u** [comment]
Do you mean you're going to try hostgator? If so I can't promise it will work since I've never personally tested it there but it may work fine. Try the dev snapshot and if you have any issues please let me know and Ill do my best to help out.

**Comment by babisonashok** [comment]
thank you alot and may i know what website did you use

**Comment by ty2u** [comment]
I installed Virtualmin on a VPS at this host: https://www.digitalocean.com/?refcode=e7fb4324ab12

**Comment by babisonashok** [comment]
hey bro i decided to go with digital ocean but what your referral code so you can get that $25 thing

**Comment by ty2u** [comment]
Hello,

I put my referral link in my previous post. Thanks!

**Comment by babisonashok** [comment]
hey I need some help with installing the script do you mind adding me on skype so i can show you my problem skype : babisonashok1999

**Comment by ty2u** [comment]
I don't use skype. Feel free to post some screenshots or a video if you
like.

**Comment by babisonashok** [comment]
theres a readme file in million dollar file 2015 and I dont know if i did step 1 properly and step 2 properly I did step 2 with file zilla by moving the script files in public.html and change permissions is that correct

**Comment by babisonashok** [comment]
this is step 2 
![untitled](https://cloud.githubusercontent.com/assets/13056576/9764432/1e7478ca-56dd-11e5-8c7a-5b7a883fa5ed.jpg)

**Comment by babisonashok** [comment]
this is step 2 i did 
![untitled](https://cloud.githubusercontent.com/assets/13056576/9764463/574069fc-56dd-11e5-8fe5-c94673d133b5.jpg)

**Comment by ty2u** [comment]
You shouldn't be using root. The website should have a user to log in with.
You should change the user and owner on all files and folders within the
public_html folder to that user.

**Comment by ty2u** [comment]
also public_html normally isn't in the root of the drive so maybe you
haven't set up you Web server properly.

**Comment by babisonashok** [comment]
i was told to add the public_html ill delete it but how do i change the root user do i do it with concole access

**Comment by babisonashok** [comment]
i deleted the public file how do i add the script into the system

**Comment by ty2u** [comment]
Did you get a server at digitalocean.com? If so how did you set it up? What
is or preset did you use? You may have to install a Web server on your
system. You may wish to use one of the presets. Or you may wish to install
a control panel like virtualmin to help manage it.

**Comment by babisonashok** [comment]
i did use digitalocean i installed mysql as preset

**Comment by ty2u** [comment]
Ok, well that will only put the database system on there. You should use 
the LAMP on 14.04 application or even the WordPress preset and install 
the mds in a subfolder under your WordPress site and use WordPress as a 
sort of front end to manage other features of your site if you like. You 
can do it either way depending on how you want to run your site. Or if 
you want to use Virtualmin just use the Ubuntu 14.04 and then install 
Virtualmin on it and it will setup a LAMP system for you. However you 
probably want to use a 1GB system, I have had issues getting systems to 
run stable on 512MB systems without manually tweaking things quite a bit.

**Comment by babisonashok** [comment]
i changed it to wordpress and added wordpress to my server here is my server 104.131.240.146
I now need to add the script to the server with filezilla could you please help me with that do I add the script files to var/www/   and change permission?

**Comment by ty2u** [comment]
You just have to upload the files to your web servers folder and 
normally the file owner and group is the same as the user the web server 
runs on. The file permissions are then normally 644 and the folder 
permissions are usually 755. If they are owned by the same user that the 
web server runs on then the web server should then be able to read and 
write to all the files and folders.

**Comment by babisonashok** [comment]
on the readme file in milliondollarscript 2015 folder it says to change the permissionss

**Comment by babisonashok** [comment]
and it says permission denied

**Comment by babisonashok** [comment]
should i make a video and show you

**Comment by ty2u** [comment]
You can make a video if you like. But I think it sounds like maybe you just don't understand the user permissions in general. If your web server is running your site as the user www-data then you must change the owner and group of the files and folders to www-data. In this case the files and folders could likely run as their default permissions which can be 755 for folders and 644 for files. But you have to change their owner and group to www-data. Some linux distributions will run the web server as different users.

Did you use the WordPress on 14.04 distribution on digital ocean? I could setup an identical droplet to test with.

**Comment by babisonashok** [comment]
hey heres the video
 http://www.mediafire.com/download/1htvjvxo3cpb95a/My+Movie.mp4 
could you please make a video about how to install milliondollarscript on digitalocean 
Im really stuggling and it would be really helpful for me and maybe for others aswell

**Comment by ty2u** [comment]
It looks like your webserver isn't setup properly perhaps. There should be an html folder within the www folder by default which is where the files should go.

**Comment by ty2u** [comment]
If you still have issues after I can make a video on the weekend for you =)

**Comment by babisonashok** [comment]
please make a video that would be fantastic you will help me and others for sure

**Comment by babisonashok** [comment]
is it possible to create a website with just the milliondollarscript it self without wordpress or anything else

**Comment by ty2u** [comment]
You can if you like. You would just have to edit the code yourself to 
change your site.

**Comment by babisonashok** [comment]
could you please make a video with wordpress and without it it would be fantastic thanks soo much

**Comment by ty2u** [comment]
Well I probably could put them in the same video somehow. I am also creating a WordPress plugin for the next version so there will some day only be WordPress but that is likely still a ways off.

**Comment by babisonashok** [comment]
your amazing thanks so much

**Comment by babisonashok** [comment]
Million Dollar Script - Database Installation

Please fill in the form and click install.
Please make sure that the MySQL user has all the permissions to use the database (Admin privileges).
- config.php is writeable. (OK)
- pixels/ directory is writeable. (OK)
- admin/temp directory is writeable. (OK)
- lang/english.php file is not writable. Give write permissions (666) to lang/english.php file
- upload_files/docs/ directory is not writable. Give write permissions (777) to upload_files/docs/ directory
- upload_files/images/ directory is not writable. Give write permissions (777) to upload_files/docs/ directory
 

Paths and Locations

Site's HTTP URL (address)	 
http://159.203.75.218/

Recommended: http://159.203.75.218/
Server Path to Admin	 
/var/www/html/admin/

Recommended: /var/www/html/admin/
Path to upload directory	 

Recommended: /var/www/html/upload_files/
HTTP URL to upload directory	 

Recommended: http://159.203.75.218/upload_files/
NOTES
- Server Path to Admin is the full path to your admin directory, including a slash at the end
- The Site's HTTP URL must include a slash at the end
- Use the recommended settings unless you are sure otherwise
Also, don't forget to set the permissions of the admin/temp/ directory to 777.
The script must be able to write to temp/ dir in the admin
The script also needs to be able to write to the pixels/ directory (chmod 777) 
 

Mysql Settings
Mysql Database Username	 
root
Mysql Database Password	 
••••••••••
Mysql Database Name	 
Mysql Server Hostname	 
localhost
Install





Hey is this correct what is my database name?

**Comment by ty2u** [comment]
I'm not sure what your database name is but your username and database 
name may be wordpress if you used that install. You would have had to 
check your wp-config.php file but it seems like you may have deleted it. 
If so you might want to simply start over fresh and check that file 
before you delete it to get your database info.

Also you are getting these messages:

  * lang/english.php file is not writable. Give write permissions (666)
    to lang/english.php file
  * upload_files/docs/ directory is not writable. Give write permissions
    (777) to upload_files/docs/ directory
  * upload_files/images/ directory is not writable. Give write
    permissions (777) to upload_files/docs/ directory

**Comment by babisonashok** [comment]
hey how do you create a database and a database user and how do i add mysql user to database thanks

**Comment by babisonashok** [comment]
i made a backup copy of the files do you want me to add it back into the var/www/html directory

**Comment by babisonashok** [comment]
should i give permissions to those 3 directories thanks

**Comment by ty2u** [comment]
Look in your backup and find the wp-config.php file and your username and password and database info is in there.

**Comment by babisonashok** [comment]
my username is wordpress and database name is wordpress

**Comment by babisonashok** [comment]
should i add the backup files back into the var/www/html/

**Comment by babisonashok** [comment]
i found my username and database name

**Comment by babisonashok** [comment]
shoudl i add privileges to the 3 directories for full privilege to mysql

**Comment by ty2u** [comment]
You dont have to put the files back if you dont want to use WordPress. Just use the database info to install MDS.

The file permissions are unrelated to the database. You have to have them writeable by the web server so that people can upload files.

**Comment by babisonashok** [comment]
i got it successfully installed thanks soo much bro

**Comment by ty2u** [comment]
You're welcome. Good luck!
