### ISSUE TITLE
Unable to create 1000 x 1000 grid

### ISSUE THREAD

**Issue by deuxbiers** [MillionDollarScript/MillionDollarScript#27]
I'm trying to create a grid 1000x1000. First thing I find is when I try to change the block size under block configuration, I get an error if I change it to anything other than the default 10x10. The error is in the block graphics configuration saying the size is invalid.

So if leave the block size to 10x10 the next error I get is when I setup Price Zones it doesn't display the grid, just a large square with an image placeholder in the top left corner.

Lastly, when I try to edit the grid background the grid renders really slowly and isn't responsive. Am I therefore restricted to a smaller grid (100x100) or can you suggest another way around this?

**Comment by ty2u** [comment]
Hi there,

Which version of the script are you using? If you haven't given the development snapshot a try that might fix your error of changing the block size. If you are using that then I will have to look into that and fix it.

In order to create such a large grid you would probably have to increase the amount of memory allotted to PHP. However that may require a fair amount of memory to create a grid that large. I plan to implement the ability to do this in the future using AJAX with each block being separately constructed and loaded. This should allow creation of grids of just about any size.

But for now it is limited by the amount of memory allotted to PHP which you can change in the config. Some hosts won't let you change this value and it also could affect the performance of your site if you set it too high.

Good luck!

Ryan

**Comment by deuxbiers** [comment]
Hi, I'm using the development version. In hindsight I think a grid size of 100 might be more user friendly anyway. To your knowledge has anyone developed a site with a responsive grid. I imagine this would need a different width:height ratio at different screen sizes.

**Comment by ty2u** [comment]
I think people have created separate grids for each screen size and implemented the screen size detection in their index.php file to display the proper iframe for each grid based on the detected screen size.

**Comment by deuxbiers** [comment]
Okay, fresh install but now I'm getting this error in the main config page:

Strict Standards: Declaration of smtp_message_class::SendMessageBody() should be compatible with email_message_class::SendMessageBody(&$data) in /home/deuxbiers/picassosparadise.com/millionpixelart/mail/smtp_message.php on line 594

**Comment by ty2u** [comment]
Are you using the development snapshot now? I thought that I fixed that in
the development snapshot at one point. You also should lower the error
reporting in your PHP settings to a better production value. I think that
the error is safe to ignore but if it doesn't send emails and maybe not.

**Comment by deuxbiers** [comment]
Okay, I fixed the smtp error by copying all the files from the dev version in the mail folder.
I'm still getting a strange error in the payment modules. At the top of the screen is this:

Mac OS X 	2°âATTRWk¸â˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTRèÜœ¾â˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTR»Æàiâ˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTRÃËâ˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTRšðÏâ˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTR%®`bâ˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTR **â˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTRù¤¶â˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTR(Ëéâ˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTR %'Oâ˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿMac OS X 	2°âATTR8â˜G˜Gcom.apple.quarantine0001;559a775d;Google\x20Chrome.app;C223AFDE-87D5-4D4F-A649-D1BE19916EA3This resource fork intentionally left blank ÿÿ

**Comment by ty2u** [comment]
That's definitely a strange error. I have no idea where it comes from or what it means but I don't have a Mac and I don't use Google Chrome so I'm not sure where it could come from. Maybe you are on Mac and have caused some sort of corrupt file.

**Comment by deuxbiers** [comment]
Hi Ryan,

Thanks for your help, I seem to have it working now. By using a combination
of the dev and version 2.015 files.

My next question is can I edit the screen where users buy blocks? On the
Price Table I would like to add a graphic to show the price zones as they
appear on the grid. I guess I need to delve into a php file. Can you point
me in the right direction.

Thanks

Gareth

*G*

*areth Pugh, Director*
PigeonTech WebDesign Ltd | Tel: 01629 258 079 | Mobile: 07811 002 162 |
www.pigeontech.co.uk

[image: http://www.facebook.com/pigeontechwebdesign]
<http://www.facebook.com/pigeontechwebdesign>

[image: https://twitter.com/PigeonTech_IT]
<https://twitter.com/PigeonTech_IT>

This e-mail is confidential and may contain legally privileged information.
If you are not the intended recipient, you should not copy, distribute,
disclose or use the information it contains. Please e-mail the sender
immediately and delete this message from your system. E-mails are
susceptible to corruption, interception and unauthorised amendment; we do
not accept liability for any such changes, or for their consequences. You
should be aware, that the company may monitor your emails and their content.

Registered in England and Wales. No. 07009453 | Registered office: 3 St
Giles Mews, Church Street, Matlock. DE4 3BZ

**Comment by ty2u** [comment]
Hi there,

I'm not 100% sure what you're trying to do but normally you should be 
able to just edit the file as in the current URL you're at. For example 
if you are on /users/order_pixels.php you should be able to edit the 
/users/order_pixels.php somewhere in the file where it starts outputting 
HTML.

I'll be going away on a trip for a couple weeks so responses might be 
slower until I get back.

Good luck!

Ryan


> Hi Ryan,
>
> Thanks for your help, I seem to have it working now. By using a 
> combination
> of the dev and version 2.015 files.
>
> My next question is can I edit the screen where users buy blocks? On the
> Price Table I would like to add a graphic to show the price zones as they
> appear on the grid. I guess I need to delve into a php file. Can you point
> me in the right direction.
>
> Thanks
>
> Gareth
>
> *G*
>
> *areth Pugh, Director*
> PigeonTech WebDesign Ltd | Tel: 01629 258 079 | Mobile: 07811 002 162 |
> www.pigeontech.co.uk
>
> [image: http://www.facebook.com/pigeontechwebdesign]
> <http://www.facebook.com/pigeontechwebdesign>
>
> [image: https://twitter.com/PigeonTech_IT]
> <https://twitter.com/PigeonTech_IT>
>
> This e-mail is confidential and may contain legally privileged 
> information.
> If you are not the intended recipient, you should not copy, distribute,
> disclose or use the information it contains. Please e-mail the sender
> immediately and delete this message from your system. E-mails are
> susceptible to corruption, interception and unauthorised amendment; we do
> not accept liability for any such changes, or for their consequences. You
> should be aware, that the company may monitor your emails and their 
> content.
>
> Registered in England and Wales. No. 07009453 | Registered office: 3 St
> Giles Mews, Church Street, Matlock. DE4 3BZ
>
