### ISSUE TITLE
Fix default capabilities option not loading.

### ISSUE THREAD

**Issue by ryvix** [milliondollarscript/milliondollarscript#29]
***In GitLab by @Ryvix on Dec 8, 2023, 21:54 EST:***

*Migrated from GitLab: https://gitlab.com/MillionDollarScript/milliondollarscript-two/-/work_items/28*

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Dec 8, 2023, 21:54 EST:***

added #17 as parent issue
