### ISSUE TITLE
images not uploading after users purchase pixels

### ISSUE THREAD

**Issue by billboar** [MillionDollarScript/MillionDollarScript#30]
i'm at a loose end because after users purchase pixels they are unable to upload any images. does anyone know why this is? 
user clicks on "manage pixels" then picks a red block, then they are promted to select an image in line with the size of a block and then as soon as they click upload it does nothing, it just reverts back to the same page. I have tried to upload different image types but nothing. 
I'm using the latest version and everything else seems to be working fine, If i allow users to upload images first they upload fine. I like using the advance way of buying pixels as users can select pixels first then upload an image after payment and this works better as it allows me to design an image for users if need be and it's much easier for users imo. 

Any help/advice greatly appreciated as this is holding me back.

**Comment by ty2u** [comment]
Hi there,

What version of the script are you using?

Do you see any errors in your web server's error logs?

**Comment by billboar** [comment]
Thanks for getting back to me Ryan, 

I'm using the latest script (development snapshot). no errors in the logs however i did some experimenting and found that if i purchased the 0 block (top left corner) it will upload an image to that. If i own the 0 block and try to upload an image to another block say the 227 block for example it will upload that image to block 0 (even though i'm on block 227). So for some reason only the 0 block will accept an image and all others won't accept anything, and if you own block 0 an image will always upload to that block. 

I did reinstall the script just to make sure i didn't do anything wrong when i installed it but that did nothing. Everything else seems fine. 

Hopefully (fingers crossed) it's an easy fix. I look forward to you're reply.

Regards, 
Luke

**Comment by ty2u** [comment]
Ok I will run some tests later and see if I can reproduce it and fix it up.

**Comment by billboar** [comment]
Thanks Ryan, that would be great if you can find a fix for it. 

I'm aware that you probably spend a lot of time and effort on this and ask for nothing in return and i really appreciate it, so I will bung you a few quid when everything is up and running just as a thank you really.  

Anyway I look forward to hearing back from you      
Regards, 
Luke

**Comment by ty2u** [comment]
Hi there,

I was able to reproduce the issue and will work on a fix. I think there is a bug in the javascript somewhere.

**Comment by ty2u** [comment]
Well I think I fixed it.

https://github.com/MillionDollarScript/MillionDollarScript/commit/44f0cb8fb972557dcd5aef26652768e3df0ce383

**Comment by ty2u** [comment]
More fixes incoming.

**Comment by ty2u** [comment]
Ok you can download a new dev snapshot if you like. I hopefully fixed everything up properly now. If not just let me know =)

**Comment by billboar** [comment]
Thank you Ryan, for doing it all so quick as well :-) 
I have tested it out and yes I can now upload images so that's all good. 
I just thought I would let you know that there is still a glitch, if you are to purchase blocks that are separate from each other (say block 2 and 378) the system won't recognise it and will join the blocks up. So it will say that you have loads of pixels when you don't. It doesn't actually take up any additional blocks but obviously it won't allow you to upload a photo properly due to it thinking it's covering a very large size. I've got a feeling it's a bit tricky to separate the blocks in to separate sections in the same order and it doesn't really affect most orders as people don't generally buy separate blocks away from each other. Personally I would just write in the instructions that all purchases must ensure all blocks are joined up and not separate from each other. If they want another area they are just to make a new order. Unless you're pedantic then you'll be itching to fix it!!! Let me know what you think.  

Anyway thank you once again for sorting it and quickly as well much appreciated. 
Take care, 
Luke

**Comment by ty2u** [comment]
Hmm that does seem like a tricky issue alright.

So you think it should force them to pick blocks that are next to each 
other in a single order?

Only other solution I could think is if it correctly only charged for 
the selected blocks and still used a larger image but only displayed it 
through where they have selected the blocks. Of course then people would 
want to reposition the image over their selected blocks to get a 
different part of the image to show through.

**Comment by billboar** [comment]
No I don't think you should force people to pick blocks that are adjacent to each other, I can see a lot of issues cropping up from that if you scripted that in to force that and it's not worth the hassle. I appreciate that it is technical a fault but it won't really affect anyone just the awkward gits who want to buy pixels all over the board in one pop!! 

Using a larger image wouldn't be viable really, it would cause too much confusion. If you purchased block 0 and 9999 at the same time you would need a very large image (a million pixels!!).

The job you did on fixing it is near faultless. If i was you I would leave it for now and see how it runs. I'm using the new script you updated today and so far everything seem fine. 

I will keep you updated if I come across any other issues. 

Thanks Ryan, 
Take it easy, 
Luke.
