### ISSUE TITLE
Large image not going to edge of grid when ordering.

### ISSUE THREAD

**Issue by ryvix** [milliondollarscript/milliondollarscript#30]
***In GitLab by @Ryvix on Dec 8, 2023, 21:54 EST:***

*Migrated from GitLab: https://gitlab.com/MillionDollarScript/milliondollarscript-two/-/work_items/29*

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Dec 8, 2023, 21:54 EST:***

added #17 as parent issue
