### ISSUE TITLE
412 Error

### ISSUE THREAD

**Issue by devpayal** [MillionDollarScript/MillionDollarScript#31]
After fill up the write your add form it display  the error message something like this 
412 Error

Your request got filtered out due to possible security issues.

One or more things in your request were suspicious (defective request header, invalid cookies, bad parameters)

If you think you did nothing wrong:

try again with a different browser
avoid any evil characters inside the request url
If you are the owner of the website, you can consider revising the rules of the mod_security module or turning it off from your Web Hosting Control Panel.
what was the issue please reply asap.
Thanks

**Comment by ty2u** [comment]
Mod Security conflicting.

**Comment by devpayal** [comment]
Thanks ryan it works after edit httacess file 

<IfModule mod_security.c>
  SecFilterEngine Off
  SecFilterScanPOST Off
  SecFilterInheritance Off
</IfModule>

**Comment by ty2u** [comment]
Glad you got it fixed :)
