### ISSUE TITLE
im having a problem with pixels being stretched out on my pixel page 

### ISSUE THREAD

**Issue by k138817** [MillionDollarScript/MillionDollarScript#36]
im having a problem with pixels being stretched out on my pixel page  i went from 1000 x 1000 to 1000 x 4500 and the pixels are stretched out with some being cut off at the bottom of the page http://smartcybernetics.ca/pixels

**Comment by ty2u** [comment]
Hi there,

It's possible you might have to adjust the dimensions of the iframe in your index.php file.

Ryan
