### ISSUE TITLE
incomplete pixel processing?

### ISSUE THREAD

**Issue by squeakita** [MillionDollarScript/MillionDollarScript#37]
I am getting a report that the pixel grid is messed up.
" i picked 2 boxes... then clicked one to add pic to.. small yellow smiley... then added pic and then grid messed up.... i then went in and canceled order in admin and then deleted it... still messed up... 
"

some images are showing some are not, it is almost as tho the processing is not completing.

Im not sure if this is a bug or an issue on our side/server. 
thank you for your time.

![incomplete-processing](https://cloud.githubusercontent.com/assets/17814439/13730337/9f037950-e909-11e5-94de-0eda2192f039.PNG)

**Comment by squeakita** [comment]
the yellow blocks are the issue, the images are not rendering completely.

**Comment by ty2u** [comment]
Maybe you are running out of memory. You could try moving the memory up to 64MB in the config if it's not at that. If that doesn't work maybe your host has a low limit set. Do you get any errors in your web server error logs?

**Comment by squeakita** [comment]
Hi Ryan,

 I am so sorry for the delay in response. (it's been a  Monday)

 

 I understand the issues with the program have been resolved. 

 

He re-processed the page and all of the images were restored properly except
for one, which I think he manually re-processed.

 

As far as the memory 

 

Are you speaking of a memory setting in the pixel program or for php?

in php,  memor_limit is set to 90M

 

 

Thank you for your help, but I think you can mark that down as resolved -
and not an official bug. It make be the gentleman using it. :-)

 

Thanks - Kim

 

 

  _____
