### ISSUE TITLE
The program stopped issuing ad ids

### ISSUE THREAD

**Issue by squeakita** [MillionDollarScript/MillionDollarScript#38]
I am getting reports that the script has stopped issuing ad ids. See screen shot 

![no-new-add-ids](https://cloud.githubusercontent.com/assets/17814439/14252550/c32a0a1c-fa3c-11e5-8964-296c4fb0fc3f.png)

**Comment by ty2u** [comment]
Hi there,

Do you see an errors in your web server error logs? Any errors would be very useful in tracking down the issue.

Thanks!

**Comment by squeakita** [comment]
Hi Ryan,

 I see no log files with errors.

I checked PHP error log - there is nothing.

 

He is also reporting an issue on the map order page in the admin.

Here is a screen shot.

 



 

  _____

**Comment by ty2u** [comment]
Hi there,

You may have to turn error reporting on in the main config and then browse the site and try getting it to produce errors and then check for errors.

Are you using the latest development snapshot or some other version? At one point I added an error reporting option in there. Try setting it to E_ALL

Your last screenshot didn't show up on github, maybe you tried to post one through email and it didn't work.

**Comment by squeakita** [comment]
Hi Ryan, 
Thanks for the quick response. I am sorry it took so long to get back to you. 
I went in and turned on the error reporting and went to the one page that is currently having an issue. 
I have included a screen shot of the error on the Map Order Page that is keeping the image from  displaying.

I am still unsure how he 'fixed' the issue with the ids. I suspect that issue is related. I have a question back to him asking this very question. 
Thank you for your time.

![map-of-orders-broken-image](https://cloud.githubusercontent.com/assets/17814439/14373066/44332830-fcfb-11e5-9c12-30c6e6cd559e.PNG)

**Comment by ty2u** [comment]
I fixed those errors in the latest dev snapshot, if you like you can update the 2 files here:

https://github.com/MillionDollarScript/MillionDollarScript/raw/dev/admin/ordersmap.php
https://github.com/MillionDollarScript/MillionDollarScript/raw/dev/admin/map_iframe.php

However I suspect there may be more places in the code to change in similar ways so you might see similar Undefined index errors. These might not be the cause of the issues either.

Do you see any errors that aren't notices but other error types anywhere? Feel free to post all the errors you find and I will fix them up.

**Comment by squeakita** [comment]
Thanks for the updates. I am sorry I thought I had the latest version. I suspect I will find more of those issues.

The php error log is reporting an error:

Use of undefined constant block_id - assumed 'block_id' in /admin/show_map.php on line 63
Use of undefined constant url - assumed 'url' in /admin/map_iframe.php on line 731

Also the response when I asked how the id issue was fixed:

" i didnt fix anything.. i just found the block that needed image added and i was able to edit it and once i added and image to it it assigned a number... tricky as hell to find the image to edit from the manage pixels page.. on the bottom where its blank you can still mouse over and it will show what one it is by the text.. if it dosnt have text it will just show the hand and not arrow...  "


thank you for the help

**Comment by squeakita** [comment]
To clarify, that message from " Use of undefined constant url - assumed 'url' in /admin/map_iframe.php on line 731 "

was before I updated the file - so it may be fixed in your update.

**Comment by ty2u** [comment]
I fixed those 2 errors now too in the dev branch.

**Comment by squeakita** [comment]
I am sorry, I am misunderstanding - are you telling me to upgrade to the new version? Is it possible to do that and keep the pixels we currently have in the system? If so, can you point me to the instructions for upgrading? thanks

**Comment by ty2u** [comment]
All I'm saying is I fixed those errors in the dev branch. You could update if you like but you really only have to update those 2 files. You can see the changes I made in the list of commits here: https://github.com/MillionDollarScript/MillionDollarScript/commit/b74b93f2a2718a76d165488b7f712918d67b7bf5

You only have to update those 2 files to fix those last errors you reported:
https://raw.githubusercontent.com/MillionDollarScript/MillionDollarScript/b74b93f2a2718a76d165488b7f712918d67b7bf5/admin/map_iframe.php
https://raw.githubusercontent.com/MillionDollarScript/MillionDollarScript/b74b93f2a2718a76d165488b7f712918d67b7bf5/admin/show_map.php
