### ISSUE TITLE
Cannot edit grid

### ISSUE THREAD

**Issue by johnnythinker** [MillionDollarScript/MillionDollarScript#39]
When I click edit on the manage grids page, the page is blank, white. Nothing on it at all other than left navigation menu. Anyone know what may be causing this? 
Thanks in advance, 
John

**Comment by ty2u** [comment]
Hi there,

When you enter E_ALL into the error logging option in the main config and try again do you see any errors in your web server's error log?

**Comment by johnnythinker** [comment]
Hi, thank you very much for your help.

 I think I did that correctly. When I refresh the main config page after saving with E_ALL in the field it then has the number, 8191 in the field. 

These are the last two errors on my server, the others didn't seem relevant:

[Thu Apr 14 17:14:13 2016] [error] [client 66.249.69.2] File does not exist: /home/casabitc/public_html/plugins/jquery/jquery.cookie.js
[Thu Apr 14 17:14:12 2016] [error] [client 66.249.69.2] File does not exist: /home/casabitc/public_html/plugins/jquery/jquery.form.js

**Comment by johnnythinker** [comment]
Thanks again for your help. It actually started working somehow :)

**Comment by ty2u** [comment]
Those errors don't appear to be related to this script. Maybe you have another app installed on that site there. If you see anymore errors just let me know and I'll fix them up.
