### ISSUE TITLE
HELP: Admin pages password does not work properly.

### ISSUE THREAD

**Issue by betocas** [MillionDollarScript/MillionDollarScript#40]
Hello,

I manage to install everything correctly, database running, image showing... but, for some reason I can not get to run the admin page correctly on the live website (iPage host). 

All the folder and file rights are correct "777 and 666" as per instructions.
All the paths seem to be correct too.

Here are the events:

under live page: http://www.________.com/mds/admin/ 

1. Password request appears, I enter password ("ok") 
2. It enters quickly to admin.php, and it asks again to enter password; I enter password again ("ok")
3. It displays a vertical line (part of the frame): on the right side of line is blank and on the left side of the line it asks for the password for the 3rd time; I enter the password again ("ok")
4. then it displays the "main summary menu" and that is all, the rest is blank.

I am not sure what is wrong?  I can only speculate that "admin_common.php" is not working properly.. the sessions are not being passed through ?

**BTW: on my local test page:**

http://localhost/test/admin/

It works perfectly fine!!!

I spent 2 days trying to figure it out.. and no luck !! please if someone has an idea of what am I doing wrong, I will gratefully appreciate it !!

Thank you 

This is the admin page:

![capture](https://cloud.githubusercontent.com/assets/19582593/15562575/5c7a1d42-22ce-11e6-9117-92e1f8175ab5.JPG)

**Comment by ty2u** [comment]
Hi there,

It definitely seems like some sort of specific issue to that hosts setup. Do you see any errors in any error logs if you turn on error reporting? To turn on error reporting edit config.php and change the top line that says error_reporting(0); to error_reporting(E_ALL);

Then try to browse the site and check your web servers error logs wherever it stores them. Sometimes they will put them in the same folder as the file you are accessing and sometimes they put them in other places.

There may be issues with sessions as someone else reported something but I haven't had time to mess with it myself. I have been working on a WordPress plugin though and rewriting everything from scratch but have been getting a little busy so it might take awhile longer than I thought.

**Comment by betocas** [comment]
Hello Ryan,

First, thanks for your prompt reply. Today, after a long night I figured it out what was wrong. It was on the server side. 

I had to change the php configuration to save session to temp path. 

And that worked. 

Thanks. 

Date: Thu, 26 May 2016 04:17:01 -0700

**Comment by ty2u** [comment]
Great, glad you got it fixed! If you have any other issues please let me know. Closing this ticket now.
