### ISSUE TITLE
SMTP error: it was not possible to read line from the SMTP server: the server disconnected	

### ISSUE THREAD

**Issue by betocas** [MillionDollarScript/MillionDollarScript#41]
Hello,

This is the last item to configure.. (I hope); so, when the system sends emails, it gives the following error message:

"it was not possible to read line from the SMTP server: the server disconnected"

- The queue has only one email... (the one with the error)...

The weird thing was that the first test email I sent, went through... not sure why is not working anymore?

Any ideas?

**Comment by ty2u** [comment]
Hmm, I think maybe I will have to update or use a different mail library. I updated that before and it seemed to work ok. But now people seem to have recently started reporting errors with it. I'm not sure exactly what's going on but it could be server specific I suppose.

I suspect you don't have access to your mail server logs but if so maybe it would tell you what's happening there. One thing you could try is turning on the debug output in the mail library and see if that gives any useful info.

To turn debug output on you have to edit the file at /mail/smtp.php and change line 420 from

	var $debug=0;

to

	var $debug=true;

Then save that and try the mail again and see if it gives any useful debug output.

It might be useful to also change the $html_debug variable below to true on line 438 to attempt to get a nicer looking output.

**Comment by betocas** [comment]
Thank you for your prompt response... I just changed the two vars to 'true'; I sent an email from "forgot my password link", but same error smtp error.

It did not display any errors on screen? does it suppose to display an error, or write it on a log?

Thanks!

**Comment by ty2u** [comment]
I guess maybe it didn't output properly then. Maybe it tries to but can't. It probably would have tried outputting to the screen. Maybe nothing was output or maybe it didn't get through. We could modify the output log function to put it in a file and see if that does anything.

In the same file you could try changing line 592 from

		echo $message;

to

		file_put_contents(__DIR__ . '/maildebug.log' . $message, FILE_APPEND);

Then it will hopefully try outputting a maildebug.log file in the mail folder with the messages.

I will investigate this further in a little bit. If I don't feel free to remind me.

**Comment by betocas** [comment]
So, here is what I realized... under the config menu... I had "Enable SMTP Server" checked.... I thought from previous software, that by checking it the system will send emails.. and if its not check it will not... so I had it checked "enabled"... 

By desperation, I went and "turned it off" to not use this module (so I thought).. then voila.. all the emails went through...  

Sorry for all the confusion; at least it is done.. and now I can rest... hehehe 

Regards,

Rob

**Comment by ty2u** [comment]
Oh great! I should probably have asked if you actually wanted to use an SMTP server =)

Regardless I will have to fix this at some point anyway.

Good luck!
