### ISSUE TITLE
Error When I Click "Write Your Ad"

### ISSUE THREAD

**Issue by billywhizz14** [MillionDollarScript/MillionDollarScript#43]
Hi, I am obviously doing something basic wrong. I get the following error when I click on Write Your Add, after selecting the grid I would like to buy

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS ID, t2.field_comment AS FCOMMENT FROM form_fields AS t1, form_field_translati' at line 1)

Can you please help?

**Comment by ty2u** [comment]
Hi there,

Please make sure to download the most recent development snapshot. You can get it from here: https://github.com/MillionDollarScript/MillionDollarScript/archive/dev.zip

Good luck!

**Comment by billywhizz14** [comment]
Excellent thanks
