### ISSUE TITLE
Got Error "You do not have have any new orders in progress" after click "Write Your Ads"

### ISSUE THREAD

**Issue by AzhrafAlias** [MillionDollarScript/MillionDollarScript#47]
I got Error "You do not have have any new orders in progress" after click "Write Your Ads"

Please Help
![capture](https://cloud.githubusercontent.com/assets/12478493/24365088/53456a50-1347-11e7-986d-998bce4ada11.PNG)

![image](https://cloud.githubusercontent.com/assets/12478493/24365118/652ce2a2-1347-11e7-971d-e99825de91be.png)

**Comment by ty2u** [comment]
Hi there,

Do you see any errors in your error logs? You might have an error log file in your users folder on some hosts or wherever your host happens to store them.

You might also have to enable the error reporting in your config by setting it to E_ALL

If you see no errors, can you please tell me which version of PHP and MySQL you're using as well as which version of MDS?

Which payment module are you using?

**Comment by ty2u** [comment]
Figured out this issue and pushed a fix for it =)

**Comment by AzhrafAlias** [comment]
Hye..sorry for late reply

i realised that the error come from this code in user --> write_ad.php which is at this

![image](https://cloud.githubusercontent.com/assets/12478493/24463920/cdec8402-14da-11e7-83bd-87c32a9ca2bf.png)

supposedly the code like this                                                       (mysqli_num_rows($order_result)==0)
but when i set the code manually like this (turn value 0 to 1)      (mysqli_num_rows($order_result)==1)  

then the problem is gone and i got output like this

![image](https://cloud.githubusercontent.com/assets/12478493/24464042/3ec1b18e-14db-11e7-8216-6a9a15101e7f.png)

But i should not change the code manually, so...can u help me on this...

**Comment by ty2u** [comment]
You should update your file with the one I changed shown in the commit linked above which I will link here: https://github.com/MillionDollarScript/MillionDollarScript/commit/562e6d1872094c1e01c009aba85db313a21dd86f

The image on the grid is not positioned properly by default. It gets shifted to the bottom right of the grid. Before this change you would be able to go to the next page without positioning the image on the grid which would result in the error you experienced. You would have to click the image in the bottom right of the grid and position it on the grid. But with this change it allows you to reposition the image you uploaded properly.

**Comment by AzhrafAlias** [comment]
Hi,

I already update my file...then i got  HTTP ERROR 500

![image](https://cloud.githubusercontent.com/assets/12478493/24484191/84863a24-152f-11e7-8c8c-205cc4f3a1f5.png)


please help

**Comment by ty2u** [comment]
Are you able to see any errors in your web server error logs? You might have one in the folder of the file causing the error or somewhere else depending on your web server configuration.

You should be able to just download the file here and place it into your users folder: https://raw.githubusercontent.com/MillionDollarScript/MillionDollarScript/dev/users/order_pixels.php

**Comment by AzhrafAlias** [comment]
WOW..problem solved.. 

thank you very much
