### ISSUE TITLE
unable to edit or upload logo nad write link

### ISSUE THREAD

**Issue by RhtLambed** [MillionDollarScript/MillionDollarScript#60]
while testing i make a  Privileged user ( who can buy pixel for free ). while click on edit and add text and on pixel to edit pixel(upload logo and url). then page shown empty .. 

i am attaching two screenshot , first when i booked pixel and second when i click to edit ( it is empty  ).

![issue n](https://user-images.githubusercontent.com/1018785/28244930-0abd2f80-6a17-11e7-809f-ad9aca72fb06.JPG)
![issue](https://user-images.githubusercontent.com/1018785/28244931-0b1eedf6-6a17-11e7-901b-cd85e1f13e77.JPG)

**Comment by RhtLambed** [comment]
how to so;ve issue

**Comment by ty2u** [comment]
I've been unable to reproduce this issue.

Can you please set the Error Reporting setting in the Main Config to E_ALL and then try to reproduce the error again. Then if you could check your web server error log file to see if it shows any errors those would be very helpful. There may be a lot of notices with E_ALL turned on but any warnings or errors in the logs might be helpful. Your error log file may be located in your cpanel or in an error_log file along with your other files and folders such as /mds/users/error_log

**Comment by RhtLambed** [comment]
updating config....
Notice: Constant VERSION_INFO already defined in /home/mybrandi/public_html/config.php on line 13

Notice: Constant BASE_HTTP_PATH already defined in /home/mybrandi/public_html/config.php on line 15

Notice: Constant SERVER_PATH_TO_ADMIN already defined in /home/mybrandi/public_html/config.php on line 16

Notice: Constant UPLOAD_PATH already defined in /home/mybrandi/public_html/config.php on line 17

Notice: Constant UPLOAD_HTTP_PATH already defined in /home/mybrandi/public_html/config.php on line 18

Notice: Constant MYSQL_HOST already defined in /home/mybrandi/public_html/config.php on line 19

Notice: Constant MYSQL_USER already defined in /home/mybrandi/public_html/config.php on line 20

Notice: Constant MYSQL_PASS already defined in /home/mybrandi/public_html/config.php on line 21

Notice: Constant MYSQL_DB already defined in /home/mybrandi/public_html/config.php on line 22

Notice: Constant MYSQL_PORT already defined in /home/mybrandi/public_html/config.php on line 23

Notice: Constant MYSQL_SOCKET already defined in /home/mybrandi/public_html/config.php on line 24

Notice: Constant ADMIN_PASSWORD already defined in /home/mybrandi/public_html/config.php on line 27

Notice: Constant MDS_RESIZE already defined in /home/mybrandi/public_html/config.php on line 29

Notice: Constant SITE_CONTACT_EMAIL already defined in /home/mybrandi/public_html/config.php on line 32

Notice: Constant SITE_LOGO_URL already defined in /home/mybrandi/public_html/config.php on line 35

Notice: Constant SITE_NAME already defined in /home/mybrandi/public_html/config.php on line 39

Notice: Constant SITE_SLOGAN already defined in /home/mybrandi/public_html/config.php on line 43

Notice: Constant DATE_FORMAT already defined in /home/mybrandi/public_html/config.php on line 46

Notice: Constant GMT_DIF already defined in /home/mybrandi/public_html/config.php on line 47

Notice: Constant DATE_INPUT_SEQ already defined in /home/mybrandi/public_html/config.php on line 48

Notice: Constant OUTPUT_JPEG already defined in /home/mybrandi/public_html/config.php on line 51

Notice: Constant JPEG_QUALITY already defined in /home/mybrandi/public_html/config.php on line 52

Notice: Constant INTERLACE_SWITCH already defined in /home/mybrandi/public_html/config.php on line 53

Notice: Constant USE_LOCK_TABLES already defined in /home/mybrandi/public_html/config.php on line 59

Notice: Constant BANNER_DIR already defined in /home/mybrandi/public_html/config.php on line 61

Notice: Constant EMAIL_USER_ORDER_CONFIRMED already defined in /home/mybrandi/public_html/config.php on line 68

Notice: Constant EMAIL_ADMIN_ORDER_CONFIRMED already defined in /home/mybrandi/public_html/config.php on line 69

Notice: Constant EMAIL_USER_ORDER_COMPLETED already defined in /home/mybrandi/public_html/config.php on line 70

Notice: Constant EMAIL_ADMIN_ORDER_COMPLETED already defined in /home/mybrandi/public_html/config.php on line 71

Notice: Constant EMAIL_USER_ORDER_PENDED already defined in /home/mybrandi/public_html/config.php on line 72

Notice: Constant EMAIL_ADMIN_ORDER_PENDED already defined in /home/mybrandi/public_html/config.php on line 73

Notice: Constant EMAIL_USER_ORDER_EXPIRED already defined in /home/mybrandi/public_html/config.php on line 74

Notice: Constant EMAIL_ADMIN_ORDER_EXPIRED already defined in /home/mybrandi/public_html/config.php on line 75

Notice: Constant EM_NEEDS_ACTIVATION already defined in /home/mybrandi/public_html/config.php on line 77

Notice: Constant EMAIL_ADMIN_ACTIVATION already defined in /home/mybrandi/public_html/config.php on line 78

Notice: Constant EMAIL_ADMIN_PUBLISH_NOTIFY already defined in /home/mybrandi/public_html/config.php on line 79

Notice: Constant EMAIL_USER_EXPIRE_WARNING already defined in /home/mybrandi/public_html/config.php on line 81

Notice: Constant DAYS_RENEW already defined in /home/mybrandi/public_html/config.php on line 82

Notice: Constant DAYS_CONFIRMED already defined in /home/mybrandi/public_html/config.php on line 83

Notice: Constant HOURS_UNCONFIRMED already defined in /home/mybrandi/public_html/config.php on line 84

Notice: Constant DAYS_CANCEL already defined in /home/mybrandi/public_html/config.php on line 85

Notice: Constant ENABLE_MOUSEOVER already defined in /home/mybrandi/public_html/config.php on line 86

Notice: Constant ENABLE_CLOAKING already defined in /home/mybrandi/public_html/config.php on line 87

Notice: Constant VALIDATE_LINK already defined in /home/mybrandi/public_html/config.php on line 88

Notice: Constant DISPLAY_PIXEL_BACKGROUND already defined in /home/mybrandi/public_html/config.php on line 89

Notice: Constant USE_SMTP already defined in /home/mybrandi/public_html/config.php on line 90

Notice: Constant EMAIL_HOSTNAME already defined in /home/mybrandi/public_html/config.php on line 91

Notice: Constant EMAIL_SMTP_SERVER already defined in /home/mybrandi/public_html/config.php on line 92

Notice: Constant EMAIL_SMTP_USER already defined in /home/mybrandi/public_html/config.php on line 93

Notice: Constant EMAIL_SMTP_PASS already defined in /home/mybrandi/public_html/config.php on line 94

Notice: Constant EMAIL_SMTP_AUTH_HOST already defined in /home/mybrandi/public_html/config.php on line 95

Notice: Constant POP3_PORT already defined in /home/mybrandi/public_html/config.php on line 96

Notice: Constant EMAIL_POP_SERVER already defined in /home/mybrandi/public_html/config.php on line 97

Notice: Constant EMAIL_POP_BEFORE_SMTP already defined in /home/mybrandi/public_html/config.php on line 98

Notice: Constant EMAILS_PER_BATCH already defined in /home/mybrandi/public_html/config.php on line 100

Notice: Constant EMAILS_MAX_RETRY already defined in /home/mybrandi/public_html/config.php on line 101

Notice: Constant EMAILS_ERROR_WAIT already defined in /home/mybrandi/public_html/config.php on line 102

Notice: Constant EMAILS_DAYS_KEEP already defined in /home/mybrandi/public_html/config.php on line 103

Notice: Constant USE_AJAX already defined in /home/mybrandi/public_html/config.php on line 104

Notice: Constant ANIMATION_SPEED already defined in /home/mybrandi/public_html/config.php on line 105

Notice: Constant MAX_BLOCKS already defined in /home/mybrandi/public_html/config.php on line 106

Notice: Constant MEMORY_LIMIT already defined in /home/mybrandi/public_html/config.php on line 107

Notice: Constant REDIRECT_SWITCH already defined in /home/mybrandi/public_html/config.php on line 109

Notice: Constant REDIRECT_URL already defined in /home/mybrandi/public_html/config.php on line 110

Notice: Constant ADVANCED_CLICK_COUNT already defined in /home/mybrandi/public_html/config.php on line 111

Notice: Constant TRANSITION_EFFECT already defined in /home/mybrandi/public_html/config.php on line 113

Notice: Constant ENABLE_TRANSITIONS already defined in /home/mybrandi/public_html/config.php on line 114

Notice: Constant TRANSITION_DURATION already defined in /home/mybrandi/public_html/config.php on line 115

Notice: Constant HIDE_TIMEOUT already defined in /home/mybrandi/public_html/config.php on line 116

Notice: Constant MDS_AGRESSIVE_CACHE already defined in /home/mybrandi/public_html/config.php on line 117

Notice: Constant ERROR_REPORTING already defined in /home/mybrandi/public_html/config.php on line 125
Main Configuration
Options on this page affect the running of the pixel advertising system.

Note: Make sure that config.php has write permissions turned on when editing this form. You should turn off write permission after editing this form.

Tip: Looking for where to settings for the grid? It is set in 'Pixel Inventory' -> Manage Grids. Click on Edit to edit the grid parameters.

- config.php is writeable.

**Comment by ty2u** [comment]
Those are just notices when saving the config and shouldn't be the cause of the issue. If you see any that say Warning or Error at the start then those would be something I should fix. If you turned the error reporting on then now try reproducing the original issue and see if it shows any errors there or puts them into a log file somewhere.

**Comment by RhtLambed** [comment]
hello sir,  
I have a suggestion and request , i will give you full access to you to my web hosting and all access as you need to access my website data and you solve the issue . i will very thank full to you . so please give  me you personal E-mail Id or any other source to contact you , like facebook , skype, whatsapp . to send user name and password of hosting. 

Thanks and Regards 
Rohit 
facebook :- rhtlambed
whatsapp :- +919882945635
email :- rhtlambed@gmail.com

**Comment by ty2u** [comment]
I sent you an email and removed your contact info from your comment.
