### ISSUE TITLE
mail not sent 550-Please turn on SMTP Authentication in your mail client.

### ISSUE THREAD

**Issue by RhtLambed** [MillionDollarScript/MillionDollarScript#61]
550-Please turn on SMTP Authentication in your mail client.

**Comment by ty2u** [comment]
The mail class probably requires another upgrade. When I last attempted to do this something wasn't working right so perhaps switching to a separate mailer library is necessary but would take some work.

In the meantime not using/enabling the SMTP feature should normally still allow you to be able to send mail using PHP.
