### ISSUE TITLE
error in email by gmail

### ISSUE THREAD

**Issue by RhtLambed** [MillionDollarScript/MillionDollarScript#65]
define('USE_SMTP', 'YES');
define('EMAIL_HOSTNAME', 'www.example.com');
define('EMAIL_SMTP_SERVER', 'smtp.gmail.com');
define('EMAIL_SMTP_USER', 'user@gmail.com');
define('EMAIL_SMTP_PASS', 'password');
define('EMAIL_SMTP_AUTH_HOST', 'smtp.gmail.com');
define('POP3_PORT', '587');
define('EMAIL_POP_SERVER', 'smtp.gmail.com');
define('EMAIL_POP_BEFORE_SMTP', 'NO');

please check config and tell what i have to do actual . TIA

**Comment by ty2u** [comment]
Likely your pop3 port should be 995 or 110 and pop server should probably be pop.gmail.com

I will test it when I get a chance and verify.

**Comment by RhtLambed** [comment]
Error: 99 could not connect to the host "pop.gmail.com": Cannot assign requested address
