### ISSUE TITLE
Fix not resetting order sessions when an order is completed in some cases.

### ISSUE THREAD

**Issue by ryvix** [milliondollarscript/milliondollarscript#68]
***In GitLab by @Ryvix on Dec 27, 2023, 14:12 EST:***

*Migrated from GitLab: https://gitlab.com/MillionDollarScript/milliondollarscript-two/-/work_items/67*

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Jan 12, 2024, 01:54 EST:***

mentioned in commit d810963948f4f9b96ed5d473d33e9215a6a445fa
