### ISSUE TITLE
Error post installation

### ISSUE THREAD

**Issue by vinothbabu** [MillionDollarScript/MillionDollarScript#68]
Why do i get the below error after installation of the script?

`SELECT grid_width,grid_height, block_width, block_height, bgcolor, time_stamp FROM banners WHERE (banner_id = '1')` 

A quick google of the above query lead me to this site which too has the same problem.
http://www.isimwebde.com/

**Comment by ty2u** [comment]
Hmm, it looks like that's just an SQL query. Maybe it failed for some reason or another. Did you get any errors when you ran the install.php file? At the top of the screen after installing it should have said "41 operations completed successfully" or something along those lines. And if there were any errors other than that or any errors in your web server error logs that may be helpful in figuring out the issue.

**Comment by vinothbabu** [comment]
The problem is with the download script which is available from the main website, when i went with the https://github.com/MillionDollarScript/MillionDollarScript/releases (2.1), i was not able to see that issue happening again. 

I guess you need to update the download link to latest release of github.

**Comment by ty2u** [comment]
Sorry, I forgot that page was even there. I changed the notes on it. Thanks for pointing it out.

**Comment by vinothbabu** [comment]
Also, the download option from github repo too points to older version. 

Let us ensure it all points to latest version.

**Comment by ty2u** [comment]
I can't edit the link on that pre-release dev snapshot on the releases page without adding another pre-release. But I did delete it and the 2.1 tag which was linking there.

The download on the website currently links to the correct version which is from the Clone or download button on the main page of the Github repository which links to the latest source code. It is currently this: https://github.com/MillionDollarScript/MillionDollarScript/archive/dev.zip
