### ISSUE TITLE
getting this error after installation

### ISSUE THREAD

**Issue by radhikasy** [MillionDollarScript/MillionDollarScript#69]
The file: /pixels/main1.gif doesn't exist.
Please process your pixels from the Admin section (Look under 'Pixel Admin')

**Comment by ty2u** [comment]
You have to login to the /admin area and go to Process Pixels and run that so it can create the grid the first time.

**Comment by radhikasy** [comment]
I did run the process pixels. But getting the same error.

**Comment by ty2u** [comment]
It's possible you have to adjust the permissions on some of the files and folders to allow your web server write access to them. In this case you could try to chmod the pixels folder to 777.

**Comment by radhikasy** [comment]
thanks. i created a new grid and copied main2.gif to main1.gif and now i can see the grid. but any pixels added / purchased and approved is not showing up.. the pixels show approved but not published.. dont know what is wrong with the publication Even after processing the pixels i see not published on the status of manage my pixels page.

**Comment by ty2u** [comment]
If you want to enable error logging you can set it to E_ALL & ~E_NOTICE in the MDS Admin Main config and then you can check for errors in error log files from your web server to see what's going on better.

**Comment by radhikasy** [comment]
how to set the second grid (created) to appear on home page rather the default one (installed) .

**Comment by ty2u** [comment]
You can edit that in index.php to change the BID=1 to the correct grid id # and you can get the iframe HTML in the admin as well for that entire line.

**Comment by radhikasy** [comment]
yeah. i did it but still shows the first one

**Comment by radhikasy** [comment]
how do we publish an approved pixel?

**Comment by ty2u** [comment]
The main1.gif and main2.gif files correspond to those id #s for the grids. They are automatically generated by the Process Pixels task.

They should get published automatically on successful payment. If you want to manually approve them you can do that in the admin under Approve Pixels and then click Process Pixels and click the Process Grids button.

**Comment by radhikasy** [comment]
grid selection doesn't work. need to  change the bid everytime to make it work. r there any new fixes?

**Comment by ty2u** [comment]
Do you mean grid selection for the user when buying pixels or somewhere
else? I'll take a look and see.

**Comment by ty2u** [comment]
I checked that drop down when users select a grid when ordering and it seems to work fine for me.

Maybe you are just referring to the grid that displays in your index.php file. That is hardcoded there. So if you are wanting to be able to switch between multiple grids you will have to do that however you want it to be done. You could either create a copy of the index.php file and link to it from the menu or create a select box there and hook it up to work how you want it to work if that's how you want it. Countless ways that could be accomplished I suppose. Usually people just add another page with the iframe in it and add a link to the menu of their site.
