### ISSUE TITLE
Fix payment not redirecting in some cases.

### ISSUE THREAD

**Issue by ryvix** [milliondollarscript/milliondollarscript#69]
***In GitLab by @Ryvix on Dec 27, 2023, 14:24 EST:***

*Migrated from GitLab: https://gitlab.com/MillionDollarScript/milliondollarscript-two/-/work_items/68*

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Dec 27, 2023, 14:24 EST:***

added #17 as parent issue

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Jan 18, 2024, 11:45 EST:***

removed parent issue #17
