### ISSUE TITLE
Add snapshot branch in place of dev branch.

### ISSUE THREAD

**Issue by ryvix** [milliondollarscript/milliondollarscript#70]
***In GitLab by @Ryvix on Dec 29, 2023, 15:33 EST:***

*Migrated from GitLab: https://gitlab.com/MillionDollarScript/milliondollarscript-two/-/work_items/69*

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Dec 29, 2023, 15:33 EST:***

added #17 as parent issue

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Dec 29, 2023, 16:12 EST:***

mentioned in commit d5fa74b1183d3ce8871904e8388d8443f5f785f6

**Comment by Ryvix** [comment]
***In GitLab by @Ryvix on Dec 29, 2023, 17:38 EST:***

removed parent issue #17
