### ISSUE TITLE
Can't create new grid

### ISSUE THREAD

**Issue by Henelik** [MillionDollarScript/MillionDollarScript#70]
I've successfully installed the script on a FastComet server, but can't seem to create a new grid.

Also, several tabs in the admin panel seem to not be working properly.  Under "Configuration", the language tab doesn't display any languages.  No currencies are displayed either.

When I go to the "Payment Modules" tab, it just displays the text "SELECT val FROM config WHERE `key`='COINPAYMENTS_ENABLED'". 

Is this the result of something I did wrong when installing?  How do I fix it?

**Comment by ty2u** [comment]
Hi there,

Hmm, something certainly doesn't seem quite right there. What did you do exactly?

You should be able to just upload all the files and leave their permissions on that host. You could upload the zip through the cPanel file manager or through SFTP/FTPS and extract it there.

Then you should be able to create a MySQL database and run the /admin/install.php and enter that information.

If you want me to install it for you feel free to order the installation service off the website and I can get it running for you properly. https://milliondollarscript.com/product/million-dollar-script-installation-service/

Good luck!
