### ISSUE TITLE
Skrill payment

### ISSUE THREAD

**Issue by mandarina123** [MillionDollarScript/MillionDollarScript#71]
Moneybookers change name on skrill and dont working moneybookers payment, do you have skript for SKRILL payment ?

Thank you

**Comment by ty2u** [comment]
Not at the moment, sorry.

**Comment by mandarina123** [comment]
When you define it ? :)

**Comment by ty2u** [comment]
I have no plans to rewrite that payment module. I'm working on rewriting the entire script from scratch as a WordPress plugin which will use WooCommerce and that should have a payment addon for Skrill.

I have no estimated time for when that will be ready though. I'm currently busy working on things for clients but I have been working on it sometimes and somewhat recently made some more breakthroughs so things are going pretty smoothly when I do have time to work on it.
